FROM caddy:2.7.3-builder AS builder

RUN xcaddy build --with github.com/chukmunnlee/caddy-openapi@v0.9.0

FROM caddy:2.7.3-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY api/consent-openapi.yaml /consent-openapi.yaml

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
