FROM caddy:2.5.2-builder AS builder

RUN xcaddy build --with github.com/chukmunnlee/caddy-openapi@v0.7.0

FROM caddy:2.5.2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY api/consent-openapi.yaml /consent-openapi.yaml

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
