from ninja import NinjaAPI

from .api_autogenerated import api


@api.get("/status/startup/")
def status_startup(request, a: int, b: int):
    return {"status": "OK"}

@api.get("/status/readiness/")
def status_readiness(request, a: int, b: int):
    return {"status": "OK"}
