from ninja import NinjaAPI

from .api_autogenerated import api


@api.get("/status/startup/")
def status_startup(request):
    return {"status": "OK"}

@api.get("/status/readiness/")
def status_readiness(request):
    return {"status": "OK"}
