from django.contrib import admin
from django.urls import path


from .api import api
from .api_autogenerated import api as api_autogenerated


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", api.urls),
]
